export default {
  // Common
  common: {
    search: 'Search',
    reset: 'Reset',
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    back: 'Back',
    cancel: 'Cancel',
    confirm: 'Confirm',
    submit: 'Submit',
    save: 'Save',
    update: 'Update',
    refresh: 'Refresh',
    close: 'Close',
    actions: 'Actions',
    status: 'Status',
    details: 'Details',
    loading: 'Loading...',
    noData: 'No data',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    previous: 'Previous',
    next: 'Next',
    autoRefresh: 'Auto-refresh: 30s'
  },

  // Navigation / Menu
  menu: {
    workOrders: 'Work Orders',
    dashboard: 'Dashboard',
    production: 'Production',
    productionLines: 'Production Lines',
    equipment: 'Equipment',
    quality: 'Quality',
    inspection: 'Inspection',
    defects: 'Defects',
    reports: 'Reports',
    settings: 'Settings'
  },

  // Header
  header: {
    profile: 'Profile',
    logout: 'Logout',
    language: 'Language',
    notifications: 'Notifications'
  },

  // Dashboard
  dashboard: {
    title: 'Production Dashboard',
    totalWorkOrdersToday: 'Total Work Orders Today',
    completedWorkOrders: 'Completed Work Orders',
    inProgressWorkOrders: 'In Progress Work Orders',
    exceptionWorkOrders: 'Exception Work Orders',
    productionCompletionRate: "Today's Production Completion Rate",
    targetOutput: 'Target Output:',
    actualOutput: 'Actual Output:',
    remaining: 'Remaining:',
    equipmentStatusDistribution: 'Equipment Status Distribution',
    exceptionTypeDistribution: 'Exception Type Distribution',
    equipmentFailureTop5: 'Equipment Failure TOP 5',
    dataRefreshedSuccessfully: 'Data refreshed successfully',
    failedToLoadData: 'Failed to load dashboard data'
  },

  // Work Order
  workOrder: {
    management: 'Work Order Management',
    list: 'Work Order List',
    create: 'Create Work Order',
    edit: 'Edit Work Order',
    detail: 'Work Order Detail',
    workOrderNo: 'Work Order No.',
    productCode: 'Product Code',
    batchNumber: 'Batch Number',
    plannedQty: 'Planned Qty',
    actualQty: 'Actual Qty',
    productionLine: 'Production Line',
    operator: 'Operator',
    scheduledStart: 'Scheduled Start',
    actualStart: 'Actual Start',
    actualEnd: 'Actual End',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
    notes: 'Notes',
    completionRate: 'Completion Rate',
    defectQuantity: 'Defect Quantity',
    // Placeholders
    enterWorkOrderNumber: 'Enter work order number',
    enterBatchNumber: 'Enter batch number',
    selectStatus: 'Select status',
    selectProduct: 'Select product',
    selectProductionLine: 'Select production line',
    selectEquipment: 'Select equipment',
    selectOperator: 'Select operator',
    selectStartTime: 'Select start time',
    enterNotes: 'Enter notes or instructions',
    autoGeneratedOrEnter: 'Auto-generated or enter manually',
    enterPlannedQuantity: 'Enter planned quantity',
    // Status
    status: {
      pending: 'Pending',
      inProgress: 'In Progress',
      completed: 'Completed',
      exception: 'Exception'
    },
    // Production Lines
    productionLine1: 'Production Line 1',
    productionLine2: 'Production Line 2',
    productionLine3: 'Production Line 3',
    // Actions
    startProduction: 'Start Production',
    completeProduction: 'Complete Production',
    reportException: 'Report Exception',
    // Messages
    deleteConfirmTitle: 'Delete Confirmation',
    deleteConfirmMessage: 'Are you sure you want to delete work order "{workOrderNo}"?',
    deletedSuccessfully: 'Work order deleted successfully',
    createdSuccessfully: 'Work order created successfully',
    updatedSuccessfully: 'Work order updated successfully',
    productionStarted: 'Production started successfully',
    productionCompleted: 'Production completed successfully',
    failedToLoad: 'Failed to load work orders',
    failedToDelete: 'Failed to delete work order',
    failedToCreate: 'Failed to create work order',
    failedToUpdate: 'Failed to update work order',
    failedToStart: 'Failed to start production',
    failedToComplete: 'Failed to complete production',
    failedToLoadDetail: 'Failed to load work order details',
    failedToLoadOptions: 'Failed to load options',
    enterActualQuantity: 'Please enter actual quantity produced',
    enterValidNumber: 'Please enter a valid number',
    noWorkOrdersFound: 'No work orders found',
    // Section Titles
    basicInformation: 'Basic Information',
    quantityInformation: 'Quantity Information',
    timeInformation: 'Time Information',
    // Validation
    pleaseEnterWorkOrderNumber: 'Please enter work order number',
    pleaseSelectProduct: 'Please select product',
    pleaseEnterBatchNumber: 'Please enter batch number',
    pleaseEnterPlannedQuantity: 'Please enter planned quantity',
    pleaseSelectProductionLine: 'Please select production line',
    pleaseSelectEquipment: 'Please select equipment',
    pleaseSelectOperator: 'Please select operator',
    exceptionFeatureComingSoon: 'Exception reporting feature coming soon'
  },

  // Downtime / Exception
  downtime: {
    exceptionReport: 'Downtime Exception Report',
    exceptionList: 'Downtime Exception List',
    newReport: 'New Report',
    viewExceptionList: 'View Exception List',
    reportingInstructions: 'Reporting Instructions',
    quickReportingTips: 'Quick Reporting Tips',
    // Steps
    selectEquipment: 'Select Equipment',
    exceptionType: 'Exception Type',
    descriptionAndPhoto: 'Description & Photo',
    // Form
    equipment: 'Equipment',
    description: 'Description',
    photoOptional: 'Photo (Optional)',
    response: 'Response',
    solution: 'Solution',
    reporter: 'Reporter',
    reportTime: 'Report Time',
    responseTime: 'Response Time',
    resolveTime: 'Resolve Time',
    downtime: 'Downtime',
    // Placeholders
    pleaseSelectEquipment: 'Please select equipment',
    allEquipment: 'All Equipment',
    allTypes: 'All Types',
    allStatus: 'All Status',
    enterDescription: 'Please describe the exception in detail (max 500 characters)',
    enterResponse: 'Enter your response...',
    describeSolution: 'Describe the solution...',
    // Exception Types
    exceptionTypes: {
      equipmentFailure: 'Equipment Failure',
      materialShortage: 'Material Shortage',
      qualityIssue: 'Quality Issue',
      humanError: 'Human Error',
      other: 'Other'
    },
    // Status
    status: {
      pending: 'Pending',
      inProgress: 'In Progress',
      resolved: 'Resolved'
    },
    // Actions
    respond: 'Respond',
    resolve: 'Resolve',
    submitReport: 'Submit Report',
    respondToException: 'Respond to Exception',
    resolveException: 'Resolve Exception',
    exceptionDetails: 'Exception Details',
    // Tips
    tip1: 'Select the equipment experiencing the exception',
    tip2: 'Choose the appropriate exception type',
    tip3: 'Provide a detailed description (at least 10 characters)',
    tip4: 'Optional: Upload photos to help with troubleshooting',
    tip5: 'Submit the report and the maintenance team will be notified immediately',
    // Upload
    uploadTip: 'Support JPG/PNG format, max 5MB per file, up to 3 photos',
    onlyImageAllowed: 'Only image files are allowed!',
    imageSizeLimit: 'Image size cannot exceed 5MB!',
    // Messages
    reportSubmitted: 'Report submitted successfully!',
    responseSubmitted: 'Response submitted successfully',
    exceptionResolved: 'Exception resolved successfully',
    pleaseEnterResponse: 'Please enter your response',
    pleaseDescribeSolution: 'Please describe the solution',
    failedToLoad: 'Failed to load data',
    failedToLoadEquipment: 'Failed to load equipment list',
    failedToSubmitReport: 'Failed to submit report',
    failedToSubmitResponse: 'Failed to submit response',
    failedToResolve: 'Failed to resolve exception',
    // Validation
    pleaseSelectExceptionType: 'Please select exception type',
    pleaseEnterDescription: 'Please enter description',
    descriptionLength: 'Description should be 10-500 characters'
  },

  // Charts
  charts: {
    equipmentStatus: 'Equipment Status',
    exceptionType: 'Exception Type',
    failureCount: 'Failure Count'
  }
}
