export default {
  // 通用
  common: {
    search: '搜索',
    reset: '重置',
    create: '创建',
    edit: '编辑',
    delete: '删除',
    view: '查看',
    back: '返回',
    cancel: '取消',
    confirm: '确认',
    submit: '提交',
    save: '保存',
    update: '更新',
    refresh: '刷新',
    close: '关闭',
    actions: '操作',
    status: '状态',
    details: '详情',
    loading: '加载中...',
    noData: '暂无数据',
    success: '成功',
    error: '错误',
    warning: '警告',
    info: '提示',
    previous: '上一步',
    next: '下一步',
    autoRefresh: '自动刷新: 30秒'
  },

  // 导航/菜单
  menu: {
    workOrders: '工单管理',
    dashboard: '仪表盘',
    production: '生产管理',
    productionLines: '生产线',
    equipment: '设备',
    quality: '质量管理',
    inspection: '质检',
    defects: '缺陷',
    reports: '报表',
    settings: '设置'
  },

  // 头部
  header: {
    profile: '个人中心',
    logout: '退出登录',
    language: '语言',
    notifications: '通知'
  },

  // 仪表盘
  dashboard: {
    title: '生产仪表盘',
    totalWorkOrdersToday: '今日工单总数',
    completedWorkOrders: '已完成工单',
    inProgressWorkOrders: '进行中工单',
    exceptionWorkOrders: '异常工单',
    productionCompletionRate: '今日产量完成率',
    targetOutput: '目标产量：',
    actualOutput: '实际产量：',
    remaining: '剩余产量：',
    equipmentStatusDistribution: '设备状态分布',
    exceptionTypeDistribution: '异常类型分布',
    equipmentFailureTop5: '设备故障 TOP 5',
    dataRefreshedSuccessfully: '数据刷新成功',
    failedToLoadData: '加载仪表盘数据失败'
  },

  // 工单
  workOrder: {
    management: '工单管理',
    list: '工单列表',
    create: '创建工单',
    edit: '编辑工单',
    detail: '工单详情',
    workOrderNo: '工单号',
    productCode: '产品代码',
    batchNumber: '批次号',
    plannedQty: '计划数量',
    actualQty: '实际数量',
    productionLine: '生产线',
    operator: '操作员',
    scheduledStart: '计划开始时间',
    actualStart: '实际开始时间',
    actualEnd: '实际结束时间',
    createdAt: '创建时间',
    updatedAt: '更新时间',
    notes: '备注',
    completionRate: '完成率',
    defectQuantity: '不良数量',
    // 占位符
    enterWorkOrderNumber: '请输入工单号',
    enterBatchNumber: '请输入批次号',
    selectStatus: '请选择状态',
    selectProduct: '请选择产品',
    selectProductionLine: '请选择生产线',
    selectEquipment: '请选择设备',
    selectOperator: '请选择操作员',
    selectStartTime: '请选择开始时间',
    enterNotes: '请输入备注或说明',
    autoGeneratedOrEnter: '自动生成或手动输入',
    enterPlannedQuantity: '请输入计划数量',
    // 状态
    status: {
      pending: '待处理',
      inProgress: '进行中',
      completed: '已完成',
      exception: '异常'
    },
    // 生产线
    productionLine1: '生产线 1',
    productionLine2: '生产线 2',
    productionLine3: '生产线 3',
    // 操作
    startProduction: '开始生产',
    completeProduction: '完成生产',
    reportException: '报告异常',
    // 消息
    deleteConfirmTitle: '删除确认',
    deleteConfirmMessage: '确定要删除工单 "{workOrderNo}" 吗？',
    deletedSuccessfully: '工单删除成功',
    createdSuccessfully: '工单创建成功',
    updatedSuccessfully: '工单更新成功',
    productionStarted: '生产已开始',
    productionCompleted: '生产已完成',
    failedToLoad: '加载工单失败',
    failedToDelete: '删除工单失败',
    failedToCreate: '创建工单失败',
    failedToUpdate: '更新工单失败',
    failedToStart: '开始生产失败',
    failedToComplete: '完成生产失败',
    failedToLoadDetail: '加载工单详情失败',
    failedToLoadOptions: '加载选项失败',
    enterActualQuantity: '请输入实际生产数量',
    enterValidNumber: '请输入有效数字',
    noWorkOrdersFound: '未找到工单',
    // 区块标题
    basicInformation: '基本信息',
    quantityInformation: '数量信息',
    timeInformation: '时间信息',
    // 验证
    pleaseEnterWorkOrderNumber: '请输入工单号',
    pleaseSelectProduct: '请选择产品',
    pleaseEnterBatchNumber: '请输入批次号',
    pleaseEnterPlannedQuantity: '请输入计划数量',
    pleaseSelectProductionLine: '请选择生产线',
    pleaseSelectEquipment: '请选择设备',
    pleaseSelectOperator: '请选择操作员',
    exceptionFeatureComingSoon: '异常报告功能即将上线'
  },

  // 停机/异常
  downtime: {
    exceptionReport: '停机异常报告',
    exceptionList: '停机异常列表',
    newReport: '新建报告',
    viewExceptionList: '查看异常列表',
    reportingInstructions: '报告说明',
    quickReportingTips: '快速报告提示',
    // 步骤
    selectEquipment: '选择设备',
    exceptionType: '异常类型',
    descriptionAndPhoto: '描述与照片',
    // 表单
    equipment: '设备',
    description: '描述',
    photoOptional: '照片（可选）',
    response: '响应',
    solution: '解决方案',
    reporter: '报告人',
    reportTime: '报告时间',
    responseTime: '响应时间',
    resolveTime: '解决时间',
    downtime: '停机时长',
    // 占位符
    pleaseSelectEquipment: '请选择设备',
    allEquipment: '全部设备',
    allTypes: '全部类型',
    allStatus: '全部状态',
    enterDescription: '请详细描述异常情况（最多500字）',
    enterResponse: '请输入您的响应...',
    describeSolution: '请描述解决方案...',
    // 异常类型
    exceptionTypes: {
      equipmentFailure: '设备故障',
      materialShortage: '物料短缺',
      qualityIssue: '质量问题',
      humanError: '人为错误',
      other: '其他'
    },
    // 状态
    status: {
      pending: '待处理',
      inProgress: '处理中',
      resolved: '已解决'
    },
    // 操作
    respond: '响应',
    resolve: '解决',
    submitReport: '提交报告',
    respondToException: '响应异常',
    resolveException: '解决异常',
    exceptionDetails: '异常详情',
    // 提示
    tip1: '选择出现异常的设备',
    tip2: '选择适当的异常类型',
    tip3: '提供详细描述（至少10个字符）',
    tip4: '可选：上传照片以帮助排查问题',
    tip5: '提交报告后，维护团队将立即收到通知',
    // 上传
    uploadTip: '支持 JPG/PNG 格式，单个文件最大 5MB，最多 3 张照片',
    onlyImageAllowed: '只允许上传图片文件！',
    imageSizeLimit: '图片大小不能超过 5MB！',
    // 消息
    reportSubmitted: '报告提交成功！',
    responseSubmitted: '响应提交成功',
    exceptionResolved: '异常已解决',
    pleaseEnterResponse: '请输入您的响应',
    pleaseDescribeSolution: '请描述解决方案',
    failedToLoad: '加载数据失败',
    failedToLoadEquipment: '加载设备列表失败',
    failedToSubmitReport: '提交报告失败',
    failedToSubmitResponse: '提交响应失败',
    failedToResolve: '解决异常失败',
    // 验证
    pleaseSelectExceptionType: '请选择异常类型',
    pleaseEnterDescription: '请输入描述',
    descriptionLength: '描述长度应为 10-500 个字符'
  },

  // 图表
  charts: {
    equipmentStatus: '设备状态',
    exceptionType: '异常类型',
    failureCount: '故障次数'
  }
}
